name: Continuous Integration

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust ${{ matrix.toolchain }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: thumbv7em-none-eabihf
          override: true

      - name: Install flip-link
        uses: actions-rs/install@v0.1
        with:
          crate: flip-link
          version: latest
          use-tool-cache: true

      - name: cargo build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release