on:
  push:
    branches: [ main ]
  pull_request:

name: Clippy check
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: thumbv7em-none-eabihf
          override: true
          components: clippy
      - name: cargo build release
        run: |
          cd Software
#          cargo clippy
          cd embedded
          cargo clippy
