name: Docs

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Rust ${{ matrix.toolchain }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: thumbv7em-none-eabihf
          override: true
          components: llvm-tools-preview

      - name: Run cargo doc
        run: |
          cd Software/sm4-firmware
          cargo doc
          ls target
          ls target/thumbv7em-none-eabihf

      - name: move to output directory
        run: |
          cd Software/sm4-firmware
          mkdir public && mv target/thumbv7em-none-eabihf/doc public

      - name: create index output directory
        run: cp .github/index.html Software/sm4-firmware/public

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        env:
          working-directory: Software/sm4-firmware
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
