on:
  push:
    branches: [ main ]
  pull_request:

name: Build thesis

jobs:
  thesis:
    name: Latex-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: build
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: Thesis
          args: -pdf -file-line-error -interaction=nonstopmode -outdir=out -f
          root_file: |
            thesis.tex
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: Thesis/out/thesis.pdf
